# -*- coding: utf-8 -*-
"""PorgII-tp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWtyG014kfCFMwaVnKzLc2RfTAlqhnvD

Escriba un programa que implementas las funciones necesarias para poder calcular el área y el perímetro de las siguientes figuras geométricas:
•Rectángulo
•Cuadrado
•Triangulo
•Circulo
•Polígono regular
"""

import numpy as np

def areaRectangulo(lado1,lado2) :
  area = lado1 * lado2
  return area

def areaCuadrado(lado) :
  area = lado * lado
  return area

def areaTriangulo(base, altura) :
  area = (base * altura) / 2
  return area

def areaCirulo(radio) :
  area = np.pi * radio**2
  return area

def areaPoligono(lado, lados) :
  perimetro = perimetroPoligono(lado, lados)
  angulo = 360 / lados
  apotema = lado / (2 * np.tan(np.pi / lados))
  area = (perimetro * apotema) / 2
  return area

def perimetroRectangulo(lado1,lado2) :
  perim = lado1 * 2 + lado2 * 2
  return perim

def perimetroCuadrado(lado) :
  perim = lado * 4
  return perim

def perimetroTriangulo(lado1,lado2,lado3) :
  perim = lado1 + lado2 + lado3
  return perim

def perimetroCirculo(radio) :
  perim = 2 * np.pi * radio
  return perim

def perimetroPoligono(lado, cantidad) :
  perim = lado * cantidad
  return perim

opcion = ""

while opcion != 0 :
  opcion = int(input("Elija la figura: \n1-Rectangulo \n2-Cuadrado \n3-Triangulo \n4-Circulo \n5-Poligono regular \n0 - SALIR\n"))

  if opcion == 1 :
      lado1 = float(input("Lado 1:"))
      lado2 = float(input("Lado 2:"))
      print("Area: ", areaRectangulo(lado1,lado2))
      print("Perimetro: ", perimetroRectangulo(lado1, lado2))

  elif opcion == 2 :
      lado = float(input("Lado:"))
      print("Area: ", areaCuadrado(lado))
      print("Perimetro: ", perimetroCuadrado(lado))

  elif opcion == 3 :
    base = float(input("Base:"))
    altura = float(input("Altura:"))
    print("Area: ", areaTriangulo(base, altura))
    lado1 = float(input("Lado1:"))
    lado2 = float(input("Lado2:"))
    lado3 = float(input("Lado3:"))
    print("Perimetro: ", perimetroTriangulo(lado1,lado2,lado3))

  elif opcion == 4 :
    radio = float(input("Radio:"))
    print("Area: ", areaCirulo(radio))
    print("Perimetro: ", perimetroCirculo(radio))

  elif opcion == 5 :
    lado = float(input("Lado:"))
    cantidad = float(input("Cantidad de lados:"))
    print("Area: ", areaPoligono(lado, cantidad))
    print("Perimetro: ", perimetroPoligono(lado, cantidad))

  elif opcion == 0 :
    print("Saliendo")

  else :
    print("Opción no válida")