# -*- coding: utf-8 -*-
"""ProgII-tp6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Lg4E247GvvFQjTSy6WvfFKNB3A2ZM-t
"""

cola_clientes = []

opcion = 0

while opcion != 4 :
  opcion = int(input("Ingrese la operación que desea realizar: \n1-Agregar cliente \n2-Atender siguiente en la cola \n3- Ver cola completa \n4 - Salir \n"))
  if opcion == 1 :
    cliente = input("Ingrese el nombre del cliente \n")
    preferencial = int(input("Es cliente preferencial? \n1-Si \n2-No \n"))
    if preferencial == 2 :
      cola_clientes.append(cliente)
    elif preferencial == 1 :
      cola_clientes.insert(0,cliente)
    else :
      print("Opción no válida \n")

  elif opcion == 2 :
    print("Siguiente cliente: ", cola_clientes[0])
    cola_clientes.pop(0)

  elif opcion == 3 :
    print("Cola completa: ", cola_clientes)

  elif opcion == 4 :
    print("Saliendo")

  else :
      print("Opción no válida")

